site_name: My Docs
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs

plugins:
  - ipymd:
      nbconvert_template: docs/extras/custom-template.tpl

nav:
  - Home: index.md
  - Examples: 
    - File 1: examples/file1.md
    - File 2: examples/file2.md

  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min
  - extras/pandas.css
  - extras/cell-style.css